---
- name: Add dpkg architeture i386
  ansible.builtin.lineinfile:
    dest: /var/lib/dpkg/arch
    line: i386
    create: yes
  become: yes
  changed_when: false

- name: Install Android SDK dependencies
  ansible.builtin.apt:
    name:
      - "libc6:i386"
      - "libncurses5:i386"
      - "libstdc++6:i386"
      - "lib32z1"
      - "libbz2-1.0:i386"
    update_cache: yes
  become: yes

- name: Check if cmdline-tools is already installed
  ansible.builtin.stat:
    path: "{{ android_cmdtools_root }}/latest/bin/sdkmanager"
  register: cmdline_tools_installed

- name: Download Android SDK Command Line Tools
  ansible.builtin.get_url:
    url: "{{ android_cmdtools_url }}"
    dest: /tmp/cmdtools.zip
  when: not cmdline_tools_installed.stat.exists
  delegate_to: localhost

- name: Create Android Command Line Tools root dir
  ansible.builtin.file:
    path: "{{ android_cmdtools_root }}"
    state: directory
  when: not cmdline_tools_installed.stat.exists

- name: Install Android SDK Command Line Tools
  ansible.builtin.unarchive:
    src: /tmp/cmdtools.zip
    dest: "{{ xdg_data_home }}/android/sdk/cmdline-tools/"
  when: not cmdline_tools_installed.stat.exists

- name: Check stats to determine if directory needs renameing
  ansible.builtin.stat:
    path: "{{ android_cmdtools_root }}/cmdline-tools"
  register: cmdline_dir_stat

- name: Renanaming cmdline-tools dir
  ansible.builtin.command:
    cmd: >-
      mv
      "{{ android_cmdtools_root }}/cmdline-tools"
      "{{ android_cmdtools_root }}/latest"
  when: cmdline_dir_stat.stat.exists

- name: Setting Android SDK ENV on bashrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    block: |
      export ANDROID_SDK_ROOT="{{ xdg_data_home }}/android/sdk"
      export ANDROID_HOME=$ANDROID_SDK_ROOT
      export ANDROID_AVD_HOME="$ANDROID_HOME/avd"
      export PATH="$ANDROID_HOME/cmdline-tools/latest/bin:$ANDROID_HOME/emulator:$PATH"
    marker: "# {mark} ANSIBLE MANAGED BLOCK (Android SDK)"
