---
- name: Download nodejs
  ansible.builtin.get_url:
    url: "{{ node_bin_url }}"
    dest: "{{ node_dest }}"

- name: Create nodejs directory
  ansible.builtin.file:
    path: "{{ node_dir }}"
    state: directory
    mode: o=rx
  become: yes

- name: Install nodejs
  ansible.builtin.unarchive:
    src: "{{ node_dest }}"
    remote_src: yes
    dest: "{{ node_dir }}"
    mode: o=rx
  become: yes

- name: Change PATH on bashrc to include nodejs binaries
  ansible.builtin.lineinfile:
    line: "export PATH={{ node_bin_path }}:{{ ansible_env.XDG_DATA_HOME }}/npm/bin:$PATH"
    path: "{{ ansible_env.HOME }}/.bashrc"

- name: npmrc
  ansible.builtin.blockinfile:
    path: "{{ ansible_env.XDG_CONFIG_HOME }}/npm/npmrc"
    block: |
      prefix={{ ansible_env.XDG_DATA_HOME }}/npm
      cache={{ ansible_env.XDG_CACHE_HOME }}/npm
      tmp={{ ansible_env.XDG_RUNTIME_DIR }}/npm
      init-module={{ ansible_env.XDG_CONFIG_HOME }}/npm/config/npm/init.js
    create: yes
    mode: 0600

- name: Change NPM configuration file
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.bashrc"
    line: "export NPM_CONFIG_USERCONFIG={{ ansible_env.XDG_CONFIG_HOME }}/npm/npmrc"
