---
- name: Check if nodejs is already installed
  ansible.builtin.stat:
    path: "{{ node_bin_path }}/node"
  register: node_installed

- name: Download nodejs
  ansible.builtin.get_url:
    url: "{{ node_bin_url }}"
    dest: "{{ node_dest }}"
  when: not node_installed.stat.exists

- name: Create nodejs directory
  ansible.builtin.file:
    path: "{{ node_dir }}"
    state: directory
    mode: o=rx
  when: not node_installed.stat.exists
  become: yes

- name: Install nodejs
  ansible.builtin.unarchive:
    src: "{{ node_dest }}"
    remote_src: yes
    dest: "{{ node_dir }}"
    mode: o=rx
  when: not node_installed.stat.exists
  become: yes

- name: Change PATH on bashrc to include nodejs binaries
  ansible.builtin.lineinfile:
    line: "export PATH={{ node_bin_path }}:{{ xdg_data_home }}/npm/bin:$PATH"
    path: "{{ ansible_user_dir }}/.bashrc"

- name: npmrc
  ansible.builtin.blockinfile:
    path: "{{ xdg_config_home }}/npm/npmrc"
    block: |
      prefix={{ xdg_data_home }}/npm
      cache={{ xdg_cache_home }}/npm
      tmp=/run/user/{{ ansible_user_uid }}/npm
      init-module={{ xdg_config_home }}/npm/config/npm/init.js
    create: yes
    mode: 0600

- name: Change NPM configuration file
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: "export NPM_CONFIG_USERCONFIG={{ xdg_config_home }}/npm/npmrc"

- name: Change YARN configuration file
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: "alias yarn='yarn --use-yarnrc {{ xdg_config_home }}/yarn/config'"
