---
- name: Install pip3
  ansible.builtin.apt:
    name: python3-pip
  become: yes

- name: Install pipenv
  ansible.builtin.pip:
    name: pipenv

- name: Add ~/.local/bin to PATH
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: "export PATH={{ ansible_user_dir }}/.local/bin:$PATH"
