---
- name: Uninstall cargo
  ansible.builtin.apt:
    name: 
      - cargo
      - rustc
      - rust-gdb
    state: absent
  become: yes

- name: Copy rustup install script
  ansible.builtin.copy:
    src: files/rustup.sh
    dest: /tmp/rustup.sh
    mode: 0777

- name: Rustup install script
  ansible.builtin.script:
    cmd: /tmp/rustup.sh -y
    creates: "{{ xdg_data_home }}/cargo/bin/rustup"
  environment:
    RUSTUP_HOME: "{{ xdg_data_home }}/rustup"
    CARGO_HOME: "{{ xdg_data_home }}/cargo"

- name: Config rustup env on bashrc
  ansible.builtin.lineinfile:
    path: "{{ ansible_user_dir }}/.bashrc"
    line: "export RUSTUP_HOME={{ xdg_data_home }}/rustup CARGO_HOME={{ xdg_data_home }}/cargo"
