---
- name: restart wireless network
  ansible.builtin.systemd:
    name: "{{ item }}"
    state: restarted
    daemon_reload: yes
  loop:
    - "wpa_supplicant@{{ wifi_net_dev }}.service"
    - "systemd-networkd.service"
    - "systemd-resolved.service"
  become: yes
