---
- name: Ensure presence of XDG home dirs
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
  loop:
    - "{{ xdg_config_home }}"
    - "{{ xdg_data_home }}"
    - "{{ xdg_cache_home }}"
