---
- name: Dev Tools
  hosts: localhost
  roles:
    - role: devtools
      tags: [tools, dev]
      vars:
        xdg_config_home: "{{ ansible_user_dir }}/.config"
        xdg_data_home: "{{ ansible_user_dir }}/.local/share"
        xdg_cache_home: "{{ ansible_user_dir }}/.cache"
