---
- name: Shell
  hosts: localhost
  roles:
    - role: bashrc
      vars:
        xdg_config_home: "{{ ansible_user_dir }}/.config"
        xdg_data_home: "{{ ansible_user_dir }}/.local/share"
        xdg_cache_home: "{{ ansible_user_dir }}/.cache"
      tags: [shell, bash]
