---
- hosts: localhost
  roles:
    - role: shell
      tags: [shell, basic]
    - role: linuxbrew
      tags: [pkg, basic]
    - role: nvim
      tags: [vim, nvim, tools]
    - role: awesome
      tags: [wm, desktop]
