---
- import_playbook: system.yaml
- import_playbook: shell.yaml
- import_playbook: dev.yaml
- import_playbook: nvim.yaml

- name: Dotfiles
  hosts: all
  roles:
    - role: awesome
      tags: [dotfiles, wm]

- name: Tools
  hosts: all
  roles:
    - role: misc
      vars:
        telegram_version: 2.7.4
      tags: [tools, misc]
