---
- name: System
  hosts: localhost
  vars_files: [vault.yaml]
  roles:
    - role: hardware
      tags: [sys, hw]

    - role: network
      no_log: True
      vars:
        wifi_net_dev: "{{ vault_wifi_net_dev }}"
        wifi_ssid: "{{ vault_wifi_ssid }}"
        wifi_psk: "{{ vault_wifi_psk }}"
        wifi_dhcp: "{{ vault_wifi_dhcp }}"
        wifi_addr: "{{ vault_wifi_addr }}"
        wifi_gateway: "{{ vault_wifi_gateway }}"
        wifi_dns: "{{ vault_wifi_dns }}"
      tags: [sys, net]
