---

- become: yes
  ansible.builtin.copy:
    src: "{{ item }}"
    dest: /var/cache/apt/archives/
    mode: 0666
  with_items:
    - files/canon/cnijfilter2_5.60-1_amd64.deb
    - files/canon/scangearmp2_3.60-1_amd64.deb
    - files/realtek-rtl88xxau-dkms_5.6.4.2~git20210118-0kali1_all.deb

- become: yes
  ansible.builtin.apt:
    name: [firmware-amd-graphics, cups]
    update_cache: yes

- become: yes
  ansible.builtin.apt:
    deb: "{{ item }}"
  with_items:
    - /var/cache/apt/archives/cnijfilter2_5.60-1_amd64.deb
    - /var/cache/apt/archives/scangearmp2_3.60-1_amd64.deb
    - /var/cache/apt/archives/realtek-rtl88xxau-dkms_5.6.4.2~git20210118-0kali1_all.deb

- become: yes
  community.general.modprobe:
    name: 88XXau
