---
xdg_config_home: "{{ ansible_user_dir }}/.config"
xdg_data_home: "{{ ansible_user_dir }}/.local/share"
xdg_cache_home: "{{ ansible_user_dir }}/.cache"

node_version: v14.17.0
node_bin_url: "https://nodejs.org/dist/{{ node_version }}/node-{{ node_version }}-linux-x64.tar.gz"
node_dest: /tmp/node.tar.gz
node_dir: /usr/local/lib/nodejs
node_bin_path: "{{ node_dir }}/node-{{ node_version }}-linux-x64/bin"

android_studio_release: "7302050"
android_cmdtools_url: "https://dl.google.com/android/repository/commandlinetools-linux-{{ android_studio_release }}_latest.zip"
android_sdk_root: "{{ xdg_data_home }}/android/sdk"
android_cmdtools_root: "{{ android_sdk_root }}/cmdline-tools"

go_version: go1.16.5
go_url: "https://golang.org/dl/{{ go_version }}.linux-amd64.tar.gz"
