---
- name: Install AND graphics and CUPS
  ansible.builtin.apt:
    name: [firmware-amd-graphics, cups]
    update_cache: yes
  become: yes

- name: Install deb files
  include_tasks: tasks/dotdeb.yaml
  loop:
    - cnijfilter2_5.60-1_amd64.deb
    - scangearmp2_3.60-1_amd64.deb
    - realtek-rtl88xxau-dkms_5.6.4.2~git20210118-0kali1_all.deb

- name: Probe wifi module
  community.general.modprobe:
    name: 88XXau
  become: yes
