---
- name: Install AND graphics and CUPS
  ansible.builtin.apt:
    name: [firmware-amd-graphics, cups]
    update_cache: yes
  become: yes

- name: Copy deb files
  ansible.builtin.copy:
    src: "files/{{ item }}"
    dest: /var/cache/apt/archives
    mode: 0666
  loop:
    - cnijfilter2_5.60-1_amd64.deb
    - scangearmp2_3.60-1_amd64.deb
    - realtek-rtl88xxau-dkms_5.6.4.2~git20210118-0kali1_all.deb
  become: yes

- name: Install deb files
  ansible.builtin.apt:
    deb: "/var/cache/apt/archives/{{ item }}"
  loop:
    - cnijfilter2_5.60-1_amd64.deb
    - scangearmp2_3.60-1_amd64.deb
    - realtek-rtl88xxau-dkms_5.6.4.2~git20210118-0kali1_all.deb
  become: yes

- name: Probe wifi module
  community.general.modprobe:
    name: 88XXau
  become: yes
