---
- name: Check required variables
  ansible.builtin.fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  loop: "{{ required_vars }}"

- name: Check required variables when not using DHCP
  ansible.builtin.fail:
    msg: "Variable '{{ item }}' is not defined"
  when:
    - not wifi_dhcp
    - item not in vars
  loop: "{{ required_vars_nodhcp }}"

- name: Install wpa_supplicant
  ansible.builtin.apt:
    name: wpasupplicant
    update_cache: yes
  become: yes

- name: Config wpa_supplicant
  ansible.builtin.template:
    dest: /etc/wpa_supplicant/wpa_supplicant-{{ wifi_net_dev }}.conf
    src: templates/wpa_supplicant.conf
    owner: root
    group: root
    mode: 0600
  notify: restart wireless network
  become: yes

- name: Create a systemd network unit
  ansible.builtin.template:
    dest: /etc/systemd/network/25-{{ wifi_net_dev }}.network
    src: templates/systemd.network
    owner: root
    group: root
    mode: 0644
  notify: restart wireless network
  become: yes

- name: Stop and disable conflicting services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  loop:
    - NetworkManager
    - wpa_supplicant
  become: yes

- name: Start and enable services
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
    state: started
  loop:
    - "wpa_supplicant@{{ wifi_net_dev }}"
    - "systemd-networkd"
    - "systemd-resolved"
  become: yes
