---

- name: check required variables
  ansible.builtin.fail:
    msg: "Variable '{{ item }}' is not defined"
  when: item not in vars
  with_items: "{{ required_vars }}"

- name: check required variables when not using DHCP
  ansible.builtin.fail:
    msg: "Variable '{{ item }}' is not defined"
  when:
    - not wifi_dhcp
    - item not in vars
  with_items: "{{ required_vars_nodhcp }}"

- name: install wpa_supplicant
  become: yes
  ansible.builtin.apt:
    name: wpasupplicant
    update_cache: yes

- name: config wpa_supplicant
  become: yes
  ansible.builtin.template:
    dest: /etc/wpa_supplicant/wpa_supplicant-{{ wifi_net_dev }}.conf
    src: templates/wpa_supplicant.conf
    owner: root
    group: root
    mode: 0600
  notify: restart wireless network

- become: yes
  ansible.builtin.template:
    dest: /etc/systemd/network/25-{{ wifi_net_dev }}.network
    src: templates/systemd.network
    owner: root
    group: root
    mode: 0644
  notify: restart wireless network

- become: yes
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: no
    state: stopped
  with_items:
    - NetworkManager
    - wpa_supplicant

- become: yes
  ansible.builtin.service:
    name: "{{ item }}"
    enabled: yes
    state: started
  with_items:
    - "wpa_supplicant@{{ wifi_net_dev }}"
    - "systemd-networkd"
    - "systemd-resolved"
