#!/bin/sh


if [ -d /etc/X11/xinit/xinitrc.d ]; then
	for f in /etc/X11/xinit/xinitrc.d/*; do
		[ -x "$f" ] && . "$f"
	done
	unset f
fi

xrandr --output HDMI-A-0 --primary --output DisplayPort-0 --right-of HDMI-A-0

setxkbmap -layout modbr

exec /usr/bin/awesome >> ${XDG_CACHE_HOME:-$HOME/.cache}/awesome/stdout 2>> ${XDG_CACHE_HOME:-$HOME/.cache}/awesome/stderr
