---
- name: Download Telegram
  ansible.builtin.get_url:
    url: "https://updates.tdesktop.com/tlinux/tsetup.{{ telegram_version }}.tar.xz"
    dest: "{{ ansible_env.XDG_CACHE_HOME }}/telegram.tar.xz"

- name: Unarchive Telegram
  ansible.builtin.unarchive:
    src: "{{ ansible_env.XDG_CACHE_HOME }}/telegram.tar.xz"
    dest: "{{ ansible_env.XDG_CACHE_HOME }}"
    creates: "{{ ansible_env.HOME }}/bin/telegram"
    remote_src: yes

- name: Create ~/bin directory
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/bin"
    state: directory

- name: Add ~/bin to $PATH
  ansible.builtin.lineinfile:
    line: "export PATH={{ ansible_env.HOME }}/bin:$PATH"
    path: "{{ ansible_env.HOME }}/.bashrc"

- name: Install Telegram
  ansible.builtin.copy:
    src: "{{ ansible_env.XDG_CACHE_HOME }}/Telegram/Telegram"
    dest: "{{ ansible_env.HOME }}/bin/telegram"
    mode: 0755
