---
- name: Install AwesomeWM packages
  ansible.builtin.apt:
    name: [awesome, xorg, xserver-xephyr]
    update_cache: yes
  become: yes

- name: Clone setsevireon/AwesomeConfig repo
  ansible.builtin.git:
    repo: https://github.com/setsevireon/AwesomeConfig.git
    dest: "{{ xdg_config_home }}/awesome"

- name: Copy xinitrc
  ansible.builtin.copy:
    src: files/xinitrc
    dest: "{{ ansible_env.HOME }}/.xinitrc"

- name: Add custom keymap
  ansible.builtin.copy:
    src: files/modbr.xkb
    dest: /usr/share/X11/xkb/symbols/modbr
    mode: 0644
  become: yes
