---
- name: Uninstall debian package
  ansible.builtin.apt:
    name: neovim
    state: absent
  become: yes

- name: Download binaries
  ansible.builtin.get_url:
    url: "{{ nvim_bin_url }}"
    dest: "{{ nvim_download_dest }}"

- name: Create extract diretory
  ansible.builtin.file:
    path: "{{ nvim_extract_dest }}"
    state: directory

- name: Extract archive
  ansible.builtin.unarchive:
    src: "{{ nvim_download_dest }}"
    remote_src: yes
    dest: "{{ nvim_extract_dest }}"
  changed_when: false

- name: Install binaries
  ansible.posix.synchronize:
    src: "{{ nvim_extract_dest }}/nvim-linux64/"
    dest: /usr/local/
    compress: no
    checksum: yes
  become: yes
  delegate_to: "{{ inventory_hostname }}"

- name: Install Neovim python module
  ansible.builtin.pip:
    name: neovim
