---
- name: Install language servers (NPM)
  community.general.npm:
    name: "{{ item.npm }}"
    global: yes

- name: Enamble LSP clients
  ansible.builtin.lineinfile:
    path: '{{ ansible_env.XDG_CONFIG_HOME }}/nvim/init.vim'
    line: "lua require'lspconfig'.{{ item.client }}.setup{}"
